"""init schema

Revision ID: 01b4a3e5acc6
Revises: 
Create Date: 2026-07-09 13:48:25.142397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '01b4a3e5acc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('Fact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KnowledgeSource',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clerkId', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId')
    )
    op.create_table('Chat',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KnowledgeChunk',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('knowledgeSourceId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledgeSourceId'], ['KnowledgeSource.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
CREATE INDEX knowledgechunk_embedding_hnsw_idx
ON "KnowledgeChunk"
USING hnsw (embedding vector_cosine_ops);
""")
    op.create_table('Message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chatId', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['Chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    op.drop_table('KnowledgeChunk')
    op.drop_table('Chat')
    op.drop_table('User')
    op.drop_table('KnowledgeSource')
    op.drop_table('Fact')
    op.drop_table('Organization')
    # ### end Alembic commands ###
