"""add organization fields

Revision ID: a009078853b5
Revises: 01b4a3e5acc6
Create Date: 2026-07-14 11:30:23.788289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a009078853b5'
down_revision: Union[str, Sequence[str], None] = '01b4a3e5acc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organization', sa.Column('allowedDomains', sa.Text(), nullable=True))
    op.add_column('Organization', sa.Column('widgetGreeting', sa.Text(), nullable=True))
    op.add_column('Organization', sa.Column('widgetColor', sa.String(), nullable=True))
    op.add_column('Organization', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Organization', 'updatedAt')
    op.drop_column('Organization', 'widgetColor')
    op.drop_column('Organization', 'widgetGreeting')
    op.drop_column('Organization', 'allowedDomains')
    # ### end Alembic commands ###
